spring.application.name=ticketing-tool

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=postgres
spring.datasource.password=test123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true